server: 
  port: 7001
 
eureka:
  server:
    #关闭自我保护false（缺省true）,一般不建议这么做。
    enable-self-preservation: true
    #续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    eviction-interval-timer-in-ms: 60000
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称

    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://localhost:7002/eureka/,http://localhost:7003/eureka/
